# Generated by Django 3.2.25 on 2024-05-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
